// create an object of each shrub
const arboricola = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "Scheffleras are large and graceful tropical plants often used in interior decorating. They are superb long-lived houseplants.",
    plant_type: ["Evergreen", "Shrub"],
    plant_shape: ["Hedge", "Round"],
    bloom_time: [""],
    dimensions: [ {tall: ["3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft"] }, {wide: ["3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft"] } ],
    flower_color: [""],
    flower_dimensions: [{tall: [""]}, {wide: [""]}],
    fruit_color: [""],
    leaf_color: ["Yellow", "Medium Green"],
    leaf_dimensions: [ {long: ["3 in", "4 in", "5 in"] }, {wide: ["1 in","2 in", "3 in"] }],
    bark_color: ["Yellow", "Medium Green"],
    stem_color: ["Yellow", "Medium Green"],
    sun_exposure: "sun or shade",
    soil: "well-drained",
    water_requirements: "average",
    hardiness_zone: ["9b", "10a", "10b", "11a", "11b"],
    dangerous_description: "Schefflera poisoning is due to the species containing 'sharp' calcium oxalate crystals that are insoluble and damage the cells and tissues of the animals ingesting them. For their own safety, children and household pets should be kept away from consuming this plant. In animals, the resulting damage (swelling) of exposed tissues and digestive tract may be fatal to the animal. Signs of poisoning in pets can include: oral irritation, intense burning and irritation of the mouth, lips, tongue, excessive drooling, vomiting, difficulty in swallowing",
    images: ["/images/arboricola_drawing.jpg", "/images/arboricola_1.jpg", "/images/arboricola_2.jpg"],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}

const bottlebrushBush = {
    common_name: "Dwarf Bottlebrush",
    latin_name: "Callistemon citrinus",
    brief_description: "Blood red, bottlebrush-like flower spikes cover this dwarf evergreen shrub from spring into summer. In warm, temperate regions, it will continue to bloom intermittently throughout the year. A densely branched habit with blue-green leaves that have a citrus scent when crushed. The versatile compact size is perfect for today's smaller gardens.",
    plant_type: ["Evergreen"],
    plant_shape: ["Round"],
    bloom_time: ["Spring", "Summer"],
    dimensions: [ {tall: ["3 ft"] }, {wide: ["5 ft"] } ],
    flower_color: ["Red"],
    flower_dimensions: [ {tall: ["2 in", "3 in", "4 in", "5 in"]}, {wide: ["2 in", "3 in"]} ],
    fruit_color: [""],
    leaf_color: ["Blue Green"],
    leaf_dimensions: [ {long: ["2 in", "3 in", "4 in"]}, {wide: ["1 in"]} ],
    bark_color: ["Tan", "Light Brown"],
    stem_color: ["Green"],
    sun_exposure: "full-sun",
    soil: "average moisture to dry",
    water_requirements: "low",
    hardiness_zone: ["8a", "8b", "9a", "9b", "10a", "10b", "11a", "11b"],
    dangerous_description: "No although it is commonly confused with the Buckeye bottlebrush (Aesculus parviflora), which is toxic to pets and grows in USDA zones 4 through 8",
    images: ["/images/bottlebrush_drawing.jpg", "/images/bottlebrush_1.jpg", "/images/bottlebrush_2.jpg"],
    urlFrontend: '/list/bottlebrush-bush',
    urlBackend: '/catalog/shrub/bottlebrush-bush',
    queryName: 'bottlebrush-bush',
}

const bougainvillea = {
    common_name: "Bougainvillea",
    latin_name: "Bougainvillea spectabilis",
    brief_description: "Bougainvillea is a genus of 18 flowering plants, native to South America, and in the Nyctaginaceae family. They are woody vines with a scrambling habit.",
    plant_type: ["Shrub", "Vine"],
    plant_shape: ["Arching", "Climbing", "Spreading"],
    bloom_time: ["Spring", "Summer"],
    dimensions: [ {tall: ["2 ft", "3 ft"]}, {wide: ["1 ft", "2 ft"]} ],
    flower_color: ["Pink", "White", "Purple", "Red", "Orange", "Yellow"],
    flower_dimensions: [ {tall: ["Less than 1 in"]}, {wide: ["Less than 1 in"]} ],
    fruit_color: ["Achene"],
    leaf_color: ["Light Green"],
    leaf_dimensions: [ {long: ["Less than 1 in"]}, {wide: ["Less than 1 in"]} ],
    bark_color: ["Light Brown"],
    stem_color: ["Green"],
    sun_exposure: "full sun",
    soil: "Loam (Silt), Sand, Good drainage",
    water_requirements: "Low",
    hardiness_zone: ["9b", "10b", "10a"],
    dangerous_description: "Thorns",
    images: ["/images/bougainvillea_drawing.jpg", "/images/bougainvillea_1.jpg", "/images/bougainvillea_2.jpg"],
    urlFrontend: '/list/bougainvillea',
    urlBackend: '/catalog/shrub/bougainvillea',
    queryName: 'bougainvillea',
}

const burfordiiHolly = {
    common_name: "Burford Holly",
    latin_name: "Ilex cornuta 'Burfordii'",
    brief_description: "Burdford Holly is fast growing, dense, and, because it tolerates severe pruning, can be trimmed to form a rounded large shrub, small tree (when lower branches are removed), or hedge.",
    plant_type: ["Evergreen"],
    plant_shape: ["Round"],
    bloom_time: ["Spring"],
    dimensions: [ {tall: ["4 ft", "5ft", "6 ft", "7 ft", "8 ft"] }, {wide: ["4 ft", "5ft", "6 ft", "7 ft", "8 ft"] } ],
    flower_color: ["White"],
    flower_dimensions: [ {tall: ["Less than 1 in"] }, {wide: ["Less than 1 in"] } ],
    fruit_color: ["Red"],
    leaf_color: ["Green"],
    leaf_dimensions: [ {long: ["1 in", "2 in", "3 in"] }, {wide: ["1 in", "2 in", "3 in"] } ],
    bark_color: ["Light Grey"],
    stem_color: ["Green"],
    sun_exposure: "Full sun, Partial Sun",
    soil: "good drainage, moist, occasionally dry",
    water_requirements: "moderate",
    hardiness_zone: ["7a", "7b", "8a", "8b", "9a", "9b"],
    dangerous_description: "Minor toxicity. Ingestion may cause vomiting, diarrhea, or other illness in humans.",
    images: ["/images/burfordii_holly_drawing.jpg", "/images/burfordii_holly_1.jpg", "/images/burfordii_holly_2.jpg"],
    urlFrontend: '/list/burford-holly',
    urlBackend: '/catalog/shrub/burford-holly',
    queryName: 'burford-holly',
}

const carissaHolly = {
    common_name: "Carissa Holly",
    latin_name: "Ilex cornuta 'Carissa'",
    brief_description: "This compact plant is drought and heat tolerant once established and has dense, rounded, evergreen leaves that look particularly attractive as a backdrop to colorful flowering plants. It thrives in the sun or partial shade and in slightly acidic well-drained soils.",
    plant_type: ["Shrub"],
    plant_shape: ["Dense", "Erect", "Mounding", "Rounded"],
    bloom_time: ["Spring"],
    dimensions: [ { tall: ["3 ft", "4 ft"] }, { wide: ["4 ft", "5 ft", "6 ft"] } ],
    flower_color: ["White"],
    flower_dimensions: [ {tall: ["Less than 1 in"] }, {wide: ["Less than 1 in"] } ],
    fruit_color: ["Red", "Burgundy"],
    leaf_color: ["Green"],
    leaf_dimensions: [ {long: ["1 in", "2 in", "3 in"] }, {wide: ["1 in", "2 in", "3 in"] } ],
    bark_color: ["Light Grey"],
    stem_color: ["Green", "Red", "Burgundy"],
    sun_exposure: "full sun, partial shade",
    soil: "good drainage. occasionally dry",
    water_requirements: "moderate",
    hardiness_zone: ["7b", "7a", "8b", "8a", "9b", "9a"],
    dangerous_description: "Spines/Thorns, Fruits have minor toxicity. Ingestion may cause vomiting, diarrhea, or other illness in humans.",
    images: ["/images/carissa_holly_drawing.jpg", "/images/carissa_holly_1.jpg", "/images/carissa_holly_2.jpg"],
    urlFrontend: '/list/carissa-holly',
    urlBackend: '/catalog/shrub/carissa-holly',
    queryName: 'carissa-holly',
}

const clusiaDwarf = {
    common_name: "Clusia",
    latin_name: "Clusia rosea",
    brief_description: "Dwarf clusia is a low-growing, spreading shrub with unusual foliage that can be used as an easy-care, drought-tolerant ground cover, border or accent plant.",
    plant_type: ["Shrub", "Annual"],
    plant_shape: ["Round"],
    bloom_time: ["Spring"],
    dimensions: [ { tall: ["1 ft", "2 ft"], wide: ["2 ft", "3 ft"] } ],
    flower_color: ["Pale Pink", "White"],
    flower_dimensions: [ { tall: ["Less than 1 in"], wide: ["Less than 1 in"] } ],
    fruit_color: [""],
    leaf_color: ["Green"],
    leaf_dimensions: [ { long: ["1 in", "2 in"], wide: ["1 in"] } ],
    bark_color: ["Tan"],
    stem_color: ["Green"],
    sun_exposure: "Full sun, partial sun",
    soil: "good drainage",
    water_requirements: "moderate",
    hardiness_zone: ["10a", "10b"],
    dangerous_description: "This plant is not dangerous.",
    images: ["/images/clusia_dwarf_drawing.jpg", "/images/clusia_dwarf_1.jpg", "/images/clusia_dwarf_2.jpg"],
    urlFrontend: '/list/clusia',
    urlBackend: '/catalog/shrub/clusia',
    queryName: 'clusia',
}
/*
const coontie = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "",
    plant_type: [],
    plant_shape: [],
    bloom_time: [],
    dimensions: [],
    flower_bool: ,
    flower_color: [],
    flower_dimensions: [],
    fruit_bool: ,
    fruit_color: [],
    leaf_color: [],
    leaf_dimensions: [],
    bark_color: [],
    stem_color: [],
    sun_exposure: "",
    soil: "",
    water_requirements: "",
    hardiness_zone: [],
    poisonous_bool: ,
    edible_bool: ,
    skin_irritant_bool: ,
    isDangerous: ,
    dangerous_description: "",
    images: ["", "", ""],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}
/*
const croton = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "",
    plant_type: [],
    plant_shape: [],
    bloom_time: [],
    dimensions: [],
    flower_bool: ,
    flower_color: [],
    flower_dimensions: [],
    fruit_bool: ,
    fruit_color: [],
    leaf_color: [],
    leaf_dimensions: [],
    bark_color: [],
    stem_color: [],
    sun_exposure: "",
    soil: "",
    water_requirements: "",
    hardiness_zone: [],
    poisonous_bool: ,
    edible_bool: ,
    skin_irritant_bool: ,
    isDangerous: ,
    dangerous_description: "",
    images: ["", "", ""],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}
/*
const crownOfThorns = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "",
    plant_type: [],
    plant_shape: [],
    bloom_time: [],
    dimensions: [],
    flower_bool: ,
    flower_color: [],
    flower_dimensions: [],
    fruit_bool: ,
    fruit_color: [],
    leaf_color: [],
    leaf_dimensions: [],
    bark_color: [],
    stem_color: [],
    sun_exposure: "",
    soil: "",
    water_requirements: "",
    hardiness_zone: [],
    poisonous_bool: ,
    edible_bool: ,
    skin_irritant_bool: ,
    isDangerous: ,
    dangerous_description: "",
    images: ["", "", ""],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}
/*
const driftRose = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "",
    plant_type: [],
    plant_shape: [],
    bloom_time: [],
    dimensions: [],
    flower_bool: ,
    flower_color: [],
    flower_dimensions: [],
    fruit_bool: ,
    fruit_color: [],
    leaf_color: [],
    leaf_dimensions: [],
    bark_color: [],
    stem_color: [],
    sun_exposure: "",
    soil: "",
    water_requirements: "",
    hardiness_zone: [],
    poisonous_bool: ,
    edible_bool: ,
    skin_irritant_bool: ,
    isDangerous: ,
    dangerous_description: "",
    images: ["", "", ""],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}
/*
const dwarfAllamanda = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "",
    plant_type: [],
    plant_shape: [],
    bloom_time: [],
    dimensions: [],
    flower_bool: ,
    flower_color: [],
    flower_dimensions: [],
    fruit_bool: ,
    fruit_color: [],
    leaf_color: [],
    leaf_dimensions: [],
    bark_color: [],
    stem_color: [],
    sun_exposure: "",
    soil: "",
    water_requirements: "",
    hardiness_zone: [],
    poisonous_bool: ,
    edible_bool: ,
    skin_irritant_bool: ,
    isDangerous: ,
    dangerous_description: "",
    images: ["", "", ""],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}
/*
const jasminum = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "",
    plant_type: [],
    plant_shape: [],
    bloom_time: [],
    dimensions: [],
    flower_bool: ,
    flower_color: [],
    flower_dimensions: [],
    fruit_bool: ,
    fruit_color: [],
    leaf_color: [],
    leaf_dimensions: [],
    bark_color: [],
    stem_color: [],
    sun_exposure: "",
    soil: "",
    water_requirements: "",
    hardiness_zone: [],
    poisonous_bool: ,
    edible_bool: ,
    skin_irritant_bool: ,
    isDangerous: ,
    dangerous_description: "",
    images: ["", "", ""],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}
/*
*/

// export all shrubs
exports.shrubs = [
    arboricola, 
    bottlebrushBush, 
    bougainvillea, 
    burfordiiHolly, 
    carissaHolly, 
    clusiaDwarf, 
    /*coontie, 
    croton, 
    crownOfThorns, 
    driftRose, 
    dwarfAllamanda, 
    jasminum*/
];