const arboricola = {
    common_name: "Arboricola",
    latin_name: "Schefflera arboricola",
    brief_description: "Scheffleras are large and graceful tropical plants often used in interior decorating. They are superb long-lived houseplants.",
    plant_type: ["Evergreen", "Shrub"],
    plant_shape: ["Hedge", "Round"],
    bloom_time: [""],
    dimensions: [ {tall: ["3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft"] }, {wide: ["3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft"] } ],
    flower_color: [""],
    flower_dimensions: [{tall: [""]}, {wide: [""]}],
    fruit_color: [""],
    leaf_color: ["Yellow", "Medium Green"],
    leaf_dimensions: [ {long: ["3 in", "4 in", "5 in"] }, {wide: ["1 in","2 in", "3 in"] }],
    bark_color: ["Yellow", "Medium Green"],
    stem_color: ["Yellow", "Medium Green"],
    sun_exposure: "sun or shade",
    soil: "well-drained",
    water_requirements: "average",
    hardiness_zone: ["9b", "10a", "10b", "11a", "11b"],
    dangerous_description: "Schefflera poisoning is due to the species containing 'sharp' calcium oxalate crystals that are insoluble and damage the cells and tissues of the animals ingesting them. For their own safety, children and household pets should be kept away from consuming this plant. In animals, the resulting damage (swelling) of exposed tissues and digestive tract may be fatal to the animal. Signs of poisoning in pets can include: oral irritation, intense burning and irritation of the mouth, lips, tongue, excessive drooling, vomiting, difficulty in swallowing",
    images: ["/images/arboricola_drawing.jpg", "/images/arboricola_1.jpg", "/images/arboricola_2.jpg"],
    urlFrontend: '/list/arboricola',
    urlBackend: '/catalog/shrub/arboricola',
    queryName: 'arboricola',
}

const bottlebrushBush = {
    common_name: "Dwarf Bottlebrush",
    latin_name: "Callistemon citrinus",
    brief_description: "Blood red, bottlebrush-like flower spikes cover this dwarf evergreen shrub from spring into summer. In warm, temperate regions, it will continue to bloom intermittently throughout the year. A densely branched habit with blue-green leaves that have a citrus scent when crushed. The versatile compact size is perfect for today's smaller gardens.",
    plant_type: ["Evergreen"],
    plant_shape: ["Round"],
    bloom_time: ["Spring", "Summer"],
    dimensions: [ {tall: ["3 ft"] }, {wide: ["5 ft"] } ],
    flower_color: ["Red"],
    flower_dimensions: [ {tall: ["2 in", "3 in", "4 in", "5 in"]}, {wide: ["2 in", "3 in"]} ],
    fruit_color: [""],
    leaf_color: ["Blue Green"],
    leaf_dimensions: [ {long: ["2 in", "3 in", "4 in"]}, {wide: ["1 in"]} ],
    bark_color: ["Tan", "Light Brown"],
    stem_color: ["Green"],
    sun_exposure: "full-sun",
    soil: "average moisture to dry",
    water_requirements: "low",
    hardiness_zone: ["8a", "8b", "9a", "9b", "10a", "10b", "11a", "11b"],
    dangerous_description: "No although it is commonly confused with the Buckeye bottlebrush (Aesculus parviflora), which is toxic to pets and grows in USDA zones 4 through 8",
    images: ["/images/bottlebrush_drawing.jpg", "/images/bottlebrush_1.jpg", "/images/bottlebrush_2.jpg"],
    urlFrontend: '/list/bottlebrush-bush',
    urlBackend: '/catalog/shrub/bottlebrush-bush',
    queryName: 'bottlebrush-bush',
}

const bougainvillea = {
    common_name: "Bougainvillea",
    latin_name: "Bougainvillea spectabilis",
    brief_description: "Bougainvillea is a genus of 18 flowering plants, native to South America, and in the Nyctaginaceae family. They are woody vines with a scrambling habit.",
    plant_type: ["Shrub", "Vine"],
    plant_shape: ["Arching", "Climbing", "Spreading"],
    bloom_time: ["Spring", "Summer"],
    dimensions: [ {tall: ["2 ft", "3 ft"]}, {wide: ["1 ft", "2 ft"]} ],
    flower_color: ["Pink", "White", "Purple", "Red", "Orange", "Yellow"],
    flower_dimensions: [ {tall: ["Less than 1 in"]}, {wide: ["Less than 1 in"]} ],
    fruit_color: ["Achene"],
    leaf_color: ["Light Green"],
    leaf_dimensions: [ {long: ["Less than 1 in"]}, {wide: ["Less than 1 in"]} ],
    bark_color: ["Light Brown"],
    stem_color: ["Green"],
    sun_exposure: "full sun",
    soil: "Loam (Silt), Sand, Good drainage",
    water_requirements: "Low",
    hardiness_zone: ["9b", "10b", "10a"],
    dangerous_description: "Thorns",
    images: ["/images/bougainvillea_drawing.jpg", "/images/bougainvillea_1.jpg", "/images/bougainvillea_2.jpg"],
    urlFrontend: '/list/bougainvillea',
    urlBackend: '/catalog/shrub/bougainvillea',
    queryName: 'bougainvillea',
}

const burfordiiHolly = {
    common_name: "Burford Holly",
    latin_name: "Ilex cornuta 'Burfordii'",
    brief_description: "Burdford Holly is fast growing, dense, and, because it tolerates severe pruning, can be trimmed to form a rounded large shrub, small tree (when lower branches are removed), or hedge.",
    plant_type: ["Evergreen"],
    plant_shape: ["Round"],
    bloom_time: ["Spring"],
    dimensions: [ {tall: ["4 ft", "5ft", "6 ft", "7 ft", "8 ft"] }, {wide: ["4 ft", "5ft", "6 ft", "7 ft", "8 ft"] } ],
    flower_color: ["White"],
    flower_dimensions: [ {tall: ["Less than 1 in"] }, {wide: ["Less than 1 in"] } ],
    fruit_color: ["Red"],
    leaf_color: ["Green"],
    leaf_dimensions: [ {long: ["1 in", "2 in", "3 in"] }, {wide: ["1 in", "2 in", "3 in"] } ],
    bark_color: ["Light Grey"],
    stem_color: ["Green"],
    sun_exposure: "Full sun, Partial Sun",
    soil: "good drainage, moist, occasionally dry",
    water_requirements: "moderate",
    hardiness_zone: ["7a", "7b", "8a", "8b", "9a", "9b"],
    dangerous_description: "Minor toxicity. Ingestion may cause vomiting, diarrhea, or other illness in humans.",
    images: ["/images/burfordii_holly_drawing.jpg", "/images/burfordii_holly_1.jpg", "/images/burfordii_holly_2.jpg"],
    urlFrontend: '/list/burford-holly',
    urlBackend: '/catalog/shrub/burford-holly',
    queryName: 'burford-holly',
}

const carissaHolly = {
    common_name: "Carissa Holly",
    latin_name: "Ilex cornuta 'Carissa'",
    brief_description: "This compact plant is drought and heat tolerant once established and has dense, rounded, evergreen leaves that look particularly attractive as a backdrop to colorful flowering plants. It thrives in the sun or partial shade and in slightly acidic well-drained soils.",
    plant_type: ["Shrub"],
    plant_shape: ["Dense", "Erect", "Mounding", "Round"],
    bloom_time: ["Spring"],
    dimensions: [ { tall: ["3 ft", "4 ft"] }, { wide: ["4 ft", "5 ft", "6 ft"] } ],
    flower_color: ["White"],
    flower_dimensions: [ {tall: ["Less than 1 in"] }, {wide: ["Less than 1 in"] } ],
    fruit_color: ["Red", "Burgundy"],
    leaf_color: ["Green"],
    leaf_dimensions: [ {long: ["1 in", "2 in", "3 in"] }, {wide: ["1 in", "2 in", "3 in"] } ],
    bark_color: ["Light Grey"],
    stem_color: ["Green", "Red", "Burgundy"],
    sun_exposure: "full sun, partial shade",
    soil: "good drainage. occasionally dry",
    water_requirements: "moderate",
    hardiness_zone: ["7b", "7a", "8b", "8a", "9b", "9a"],
    dangerous_description: "Spines/Thorns, Fruits have minor toxicity. Ingestion may cause vomiting, diarrhea, or other illness in humans.",
    images: ["/images/carissa_holly_drawing.jpg", "/images/carissa_holly_1.jpg", "/images/carissa_holly_2.jpg"],
    urlFrontend: '/list/carissa-holly',
    urlBackend: '/catalog/shrub/carissa-holly',
    queryName: 'carissa-holly',
}

const clusiaDwarf = {
    common_name: "Clusia",
    latin_name: "Clusia rosea",
    brief_description: "Dwarf clusia is a low-growing, spreading shrub with unusual foliage that can be used as an easy-care, drought-tolerant ground cover, border or accent plant.",
    plant_type: ["Shrub", "Annual"],
    plant_shape: ["Round"],
    bloom_time: ["Spring"],
    dimensions: [ { tall: ["1 ft", "2 ft"], wide: ["2 ft", "3 ft"] } ],
    flower_color: ["Pale Pink", "White"],
    flower_dimensions: [ { tall: ["Less than 1 in"], wide: ["Less than 1 in"] } ],
    fruit_color: [""],
    leaf_color: ["Green"],
    leaf_dimensions: [ { long: ["1 in", "2 in"], wide: ["1 in"] } ],
    bark_color: ["Tan"],
    stem_color: ["Green"],
    sun_exposure: "Full sun, partial sun",
    soil: "good drainage",
    water_requirements: "moderate",
    hardiness_zone: ["10a", "10b"],
    dangerous_description: "This plant is not dangerous.",
    images: ["/images/clusia_dwarf_drawing.jpg", "/images/clusia_dwarf_1.jpg", "/images/clusia_dwarf_2.jpg"],
    urlFrontend: '/list/clusia',
    urlBackend: '/catalog/shrub/clusia',
    queryName: 'clusia',
}

const coontie = {
    common_name: "Coontie",
    latin_name: "Zamia integrifolia",
    brief_description: "Like all cycads, the coontie has ancient origins. But this Florida plant is the only cycad native to North America. It's also the preferred food source for larvae of the rare Atala butterfly.",
    plant_type: ["Shrub", "Evergreen"],
    plant_shape: ["Round"],
    bloom_time: [""],
    dimensions: [ {tall: ["2 ft", "3 ft"]}, {wide: ["3 ft", "4 ft", "5 ft"]} ],
    flower_color: [""],
    flower_dimensions: [ {tall: [""]},{wide: [""]} ],
    fruit_color: ["Orange", "Brown"],
    leaf_color: ["Green"],
    leaf_dimensions: [{long: ["6 in", "7 in", "8 in", "9 in", "10 in", "11 in", "1 ft"]}, {wide: ["1 in"]} ],
    bark_color: ["Green"],
    stem_color: ["Green"],
    sun_exposure: "full sun, partial shade, shade",
    soil: "well drained",
    water_requirements: "low",
    hardiness_zone: ["8a", "8b", "9a", "9b", "10a", "10b", "11b"],
    dangerous_description: "Seeds, foliage, and roots are toxic.",
    images: ["/images/coontie_drawing.jpg", "/images/coontie_1.jpg", "/images/coontie_2.jpg"],
    urlFrontend: '/list/coontie',
    urlBackend: '/catalog/shrub/coontie',
    queryName: 'coontie',
}

const croton = {
    common_name: "Croton",
    latin_name: "Codiaeum variegatum var. pictum",
    brief_description: "Croton is an erect tropical evergreen shrub reaching heights of 8' but more commonly 3'.   It is a popular house shrub plant grown for its variously colored foliage or used as an exterior foundation plant, hedge, specimen plant where it is protected from frost.",
    plant_type: ["Annual", "Houseplant", "Shrub", "Poisonous"],
    plant_shape: ["Erect", "Round"],
    bloom_time: ["Fall"],
    dimensions: [ {tall: ["3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft"]}, {wide: ["1 ft", "2 ft", "3 ft", "4 ft"]} ],
    flower_color: ["White"],
    flower_dimensions: [ {tall: ["Less than 1 in"]}, {wide: ["Less than 1 in"]} ],
    fruit_color: ["Dark"],
    leaf_color: ["Gold", "Yellow", "Green", "Orange", "Pink", "Purple", "Lavender", "Red", "Burgundy", "Variegated"],
    leaf_dimensions: [ {long: ["3 in", "4 in", "5 in", "6 in"]}, {wide: ["1 in", "2 in", "3 in"]} ],
    bark_color: ["Dark brown"],
    stem_color: ["Brown", "Copper", "Cream", "Tan", "Green"],
    sun_exposure: "Full sun",
    soil: "Good drainage",
    water_requirements: "average",
    hardiness_zone: ["11b", "11a", "12a", "12b"],
    dangerous_description: "Toxic only if large quantities eaten. Skin irritation minor or lasting only for a few minutes. Allergic dermatitis with skin rash developing after repeated contact. Nausea, vomiting, diarrhea when ingested.",
    images: ["/images/croton_drawing.jpg", "/images/croton_1.jpg", "/images/croton_2.jpg"],
    urlFrontend: '/list/croton',
    urlBackend: '/catalog/shrub/croton',
    queryName: 'croton',
}

const crownOfThorns = {
    common_name: "Crown of Thorns",
    latin_name: "Euphorbia milii",
    brief_description: "Crown of Thorns is a deciduous, herbaceous, perennial shrub with bright green leaves and greenish flowers. The flowers are enclosed within long-lasting and bright bracts of red or yellow. The plant is loose in form, spiny and irregularly shaped, with thick, black spines and its historic presence in the Middle East led to the belief by some that the stems of this plant had been used in Christ's crown of thorns, hence the common name. In its country of origin (Madagascar) the plant will grow to 5 or 6 feet tall; however, in the United States, it typically grows to 3 feet, or 2 feet when grown as a houseplant.",
    plant_type: ["Annual", "Shrub", "Poisonous"],
    plant_shape: ["Round"],
    bloom_time: ["Fall", "Winter", "Spring", "Summer"],
    dimensions: [ {tall: ["3 ft", "4 ft", "5 ft", "6 ft"]}, {wide: ["1 ft", "2 ft", "3 ft"]} ],
    flower_color: ["Gold", "Yellow", "Green", "Red", "Burgundy"],
    flower_dimensions: [ {tall: ["1 in", "2 in", "3 in"]}, {wide: ["1 in", "2 in", "3 in"]} ],
    fruit_color: [""],
    leaf_color: ["Green", "Variegated", "White"],
    leaf_dimensions: [ {long: ["1 in", "2 in", "3 in"]}, {wide: ["Less than 1 in"]} ],
    bark_color: ["Grey", "Silver"],
    stem_color: ["Grey", "Silver"],
    sun_exposure: "Full sun",
    soil: "well drained",
    water_requirements: "Dry to medium moisture",
    hardiness_zone: ["9b", "9a", "10a", "11b", "11a"],
    dangerous_description: "Causes low toxicity if eaten. Causes minor skin irritation lasting for a few minutes. Ingestion can result in nausea, vomiting, and diarrhea. After some delay, contact with the skin can result in redness, swelling, and blisters.",
    images: ["/images/crown_of_thorns_drawing.jpg", "/images/crown_of_thorns_1.jpg", "/images/crown_of_thorns_2.jpg"],
    urlFrontend: '/list/crown-of-thorns',
    urlBackend: '/catalog/shrub/crown-of-thorns',
    queryName: 'crown-of-thorns',
}

const driftRose = {
    common_name: "Coral Drift Rose",
    latin_name: "Rosa 'MELdrifora'",
    brief_description: "Coral Drift Rose is a low growing shrub boasting numerous clusters of small, solitary coral colored blooms.  It grows wider than tall.",
    plant_type: ["Round"],
    plant_shape: ["Round"],
    bloom_time: ["Fall", "Spring", "Summer"],
    dimensions: [ {tall: ["1 in", "2 in"]}, {wide: ["2 ft", "3 ft"]} ],
    flower_color: ["Orange"],
    flower_dimensions: [ {tall: ["1 in", "2 in", "3 in"]}, {wide: ["1 in", "2 in", "3 in"]} ],
    fruit_color: [""],
    leaf_color: ["Green"],
    leaf_dimensions: [ {long: ["1 in", "2 in", "3 in"]}, {wide: ["1 in", "2 in"]} ],
    bark_color: [""],
    stem_color: ["Green"],
    sun_exposure: "Full sun",
    soil: "good drainage, moist",
    water_requirements: "moderate",
    hardiness_zone: ["4a", "4b", "5a", "5b", "6b", "6a", "7b","7a", "8b", "8a", "9b", "9a", "10a", "10b", "11b", "11a"],
    dangerous_description: "Thorns",
    images: ["/images/drift_rose_drawing.jpg", "/images/drift_rose_1.jpg", "/images/drift_rose_2.jpg"],
    urlFrontend: '/list/coral-drift-rose',
    urlBackend: '/catalog/shrub/coral-drift-rose',
    queryName: 'coral-drift-rose',
}

const dwarfAllamanda = {
    common_name: "Dwarf Allamanda",
    latin_name: "Allamanda cathartica",
    brief_description: "Allamanda forms a sprawling shrub or woody climber that tends to sprawl and twine itself around a support and will need to be tied to a trellis or other support. If grown outdoors in the landscape, the plants should be cut back and overwintered as indoor container plants before the first freeze.",
    plant_type: ["Houseplant", "Poisonous", "Shrub", "Vine"],
    plant_shape: ["Climbing", "Creeping", "Spreading"],
    bloom_time: ["Fall", "Winter", "Spring", "Summer"],
    dimensions: [ {tall: ["1 ft", "2 ft", "3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft", "9 ft or more"]}, {wide: ["1 ft", "2 ft", "3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft", "9 ft or more"]} ],
    flower_color: ["Gold", "Yellow"],
    flower_dimensions: [ {tall: ["3 in", "4 in", "5 in", "6 in"]}, {wide: ["3 in", "4 in", "5 in", "6 in"]} ],
    fruit_color: ["Orange"],
    leaf_color: ["Green"],
    leaf_dimensions: [ {long: ["1 in", "2 in", "3 in"]}, {wide: ["1 in", "2 in", "3 in"]} ],
    bark_color: ["Green"],
    stem_color: ["Green"],
    sun_exposure: "Full Sun",
    soil: "good drainage, occasionally wet",
    water_requirements: "moist soil",
    hardiness_zone: ["10b", "11a", "11b"],
    dangerous_description: "Poisonous through: Ingestion, dermatitis. Sap causes skin and eye irritation. Toxic only if large quantities are eaten. Skin irritation minor or lasting only for a few minutes. Symptoms may include fever, swollen lips, thirst, nausea, diarrhea; skin irritation upon contact with cell sap.",
    images: ["/images/dwarf_allamanda_drawing.jpg", "/images/dwarf_allamanda_1.jpg", "/images/dwarf_allamanda_2.jpg"],
    urlFrontend: '/list/dwarf-allamanda',
    urlBackend: '/catalog/shrub/dwarf-allamanda',
    queryName: 'dwarf-allamanda',
}

const jasminum = {
    common_name: "Jasmine",
    latin_name: "Jasminum ",
    brief_description: "Jasminium is a genus with over 200 species in the Oleaceae (olive) family.  The plants are native to tropical and subtropical areas and can be either trees, shrubs, or vines; many of the vining types make good container plants.  Members of this genus can be evergreen or deciduous. Jasmines are most well known for their heady fragranced flowers.",
    plant_type: ["Evergreen", "Shrub", "Tree", "Vine"],
    plant_shape: ["Arching", "Climbing", "Spreading", "Erect", "Round", "Creeping", "Dense", "Mounding"],
    bloom_time: ["Fall", "Winter", "Spring", "Summer"],
    dimensions: [  {tall: ["3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft", "9 ft or more"]}, {wide: ["3 ft", "4 ft", "5 ft", "6 ft", "7 ft", "8 ft", "9 ft or more"]} ],
    flower_color: ["Gold", "Yellow", "Pink", "White"],
    flower_dimensions: [ {tall: ["1 in", "2 in", "3 in"]}, {wide: ["1 in", "2 in", "3 in"]} ],
    fruit_color: ["Black"],
    leaf_color: ["Green"],
    leaf_dimensions: [ {long: ["2 in", "3 in", "4 in", "5 in"]}, {wide: ["2 in", "3 in", "4 in", "5 in"]} ],
    bark_color: ["Green", "Pale Green"],
    stem_color: ["Green", "Pale Green"],
    sun_exposure: "Full sun",
    soil: "good drainage, moist, occasionally dry",
    water_requirements: "medium moisture to wet",
    hardiness_zone: ["9B", "9a", "10b", "10a", "11b", "11a"],
    dangerous_description: "This plant is not dangerous.",
    images: ["/images/jasminum_drawing.jpg", "/images/jasminum_1.jpg", "/images/jasminum_2.jpg"],
    urlFrontend: '/list/jasminum',
    urlBackend: '/catalog/shrub/jasminum',
    queryName: 'jasminum',
}

// export all shrubs
exports.shrubs = [
    arboricola, 
    bottlebrushBush, 
    bougainvillea, 
    burfordiiHolly, 
    carissaHolly, 
    clusiaDwarf, 
    coontie, 
    croton, 
    crownOfThorns, 
    driftRose, 
    dwarfAllamanda, 
    jasminum
];